# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-29 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valispace', '0002_functions_name_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functions',
            name='name_slug',
        ),
    ]
