# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-29 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valispace', '0003_remove_functions_name_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functions',
            name='expression',
        ),
        migrations.AddField(
            model_name='functions',
            name='first_parameter_func',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_function', to='valispace.Functions'),
        ),
        migrations.AddField(
            model_name='functions',
            name='first_parameter_int',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='functions',
            name='operator',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='functions',
            name='second_parameter_func',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_function', to='valispace.Functions'),
        ),
        migrations.AddField(
            model_name='functions',
            name='second_parameter_int',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
