# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-29 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valispace', '0004_auto_20181129_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functions',
            name='first_parameter_func',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_function', to='valispace.Functions'),
        ),
        migrations.AlterField(
            model_name='functions',
            name='second_parameter_func',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_function', to='valispace.Functions'),
        ),
    ]
